name: Build
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'
      - 'rnxcmp/front-end-tools/**'
      - '.github/workflows/publish.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'
      - 'rnxcmp/front-end-tools/**'
jobs:
  build:
    name: ${{ matrix.install-mode }} | ${{ matrix.os }} | Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.11']
        install-mode: ['setup.py', 'sdist', 'wheel']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: build and install
        if: ${{ matrix.install-mode == 'setup.py' }}
        run: |
          python setup.py build
          pip install .

      - name: sdist install
        if: ${{ matrix.install-mode == 'sdist' }}
        run: |
          python setup.py sdist
          ls dist/
          python .github/pip.py install dist/hatanaka-*.tar.gz

      - name: wheel install
        if: ${{ matrix.install-mode == 'wheel' }}
        env:
          BUILD_STATIC: "${{ runner.os == 'Linux' && 'y' || 'n' }}"
        run: |
          python -m pip install wheel
          python setup.py bdist_wheel
          ls dist/
          python .github/pip.py install dist/hatanaka-*.whl

      - name: Test
        run: |
          mkdir tmp
          cd tmp
          python -m pip install pytest pytest-cov
          pytest --pyargs hatanaka -vv --cov-report=xml --cov=hatanaka.hatanaka --cov=hatanaka.general_compression --cov=hatanaka.cli

      - name: Upload coverage to Codecov
        if: ${{ matrix.install-mode == 'wheel' }}
        uses: codecov/codecov-action@v1
        env:
          OS: ${{ matrix.os }}
          PYTHON: ${{ matrix.python-version }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tmp/coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: false
