name: Publish
on:
  release:
    types: [ released ]
jobs:
  build:
    name: Build wheel | ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install prereqs
        run: python -m pip install -U build wheel setuptools pytest

      - name: Build sdist
        if: ${{ runner.os == 'Linux' }}
        run: python -m build --sdist

      - name: Build wheel
        env:
          BUILD_STATIC: "${{ runner.os == 'Linux' && 'y' || 'n' }}"
        run: python -m build --wheel

      - name: Inspect
        run: ls dist/

      - name: Run tests
        run: |
          python setup.py install
          mkdir tmp
          cd tmp
          pytest --pyargs hatanaka -vv

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*
            !dist/*.egg

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Inspect
        run: ls dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
